version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker image build --file Dockerfile . -t kanai/repo1:latest
      - docker tag kanai/repo1:latest 167551637330.dkr.ecr.ap-northeast-1.amazonaws.com/kanai/repo1:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 167551637330.dkr.ecr.ap-northeast-1.amazonaws.com/kanai/repo1:latest
      - echo Writing image definitions file...
      - printf '[{"name":"{container name}","imageUri":"%s"}]' 167551637330.dkr.ecr.ap-northeast-1.amazonaws.com/kanai/repo1:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
